### ISSUE TITLE
Preemptive canceling of loading images breaks ExperimentAnnotator

### ISSUE THREAD

**Issue by drew-sinha** [zplab/elegant#2]
Steps to reproduce failure
1. Load a new instance of gui.ExperimentAnnotator. 
2. Cancel loading of images before all images in the flipbook have loaded.
3. Attempt to advance positions via arrow (bracket does not work here; Qt eats the error?)

Expected Result: Advances position without error (in general, if there were annotations to be made, these would be saved as well before advancing)

Actual Result: AssertionError in gui.experiment_annotator:168 - 
        assert len(self.timepoints) == len(self.ris_widget.flipbook_pages)

Environment: Ubuntu/Conda+Python 3.6; updated ris_widget and elegant from 4/13 (merge with 63ddc49)

**Comment by zpincus** [comment]
Fixed in 39b4c6f855926ef76a09a7e90084c6d7d0d99305.
